ALTER SESSION SET "_ORACLE_SCRIPT"=true;  
CREATE USER alice IDENTIFIED EXTERNALLY AS 'CN=alice';
GRANT CREATE SESSION TO alice;
GRANT CREATE SESSION TO alice;
GRANT CREATE PROCEDURE TO alice;
GRANT CREATE VIEW TO alice;
GRANT CREATE TABLE TO alice;
GRANT CREATE SEQUENCE TO alice;
GRANT CREATE TRIGGER TO alice;


GRANT UNLIMITED TABLESPACE TO alice



CREATE USER teleport IDENTIFIED EXTERNALLY AS 'CN=teleport';
GRANT CREATE SESSION TO teleport;
GRANT SELECT ON dba_audit_trail TO teleport;
GRANT SELECT ON V_$SESSION TO teleport;


alter system set audit_trail=db,extended scope=spfile;

AUDIT ALL BY alice BY ACCESS;
AUDIT ALL BY alice BY ACCESS;
AUDIT SELECT TABLE, UPDATE TABLE, INSERT TABLE, DELETE TABLE BY alice BY ACCESS;
