variable "location" {
  description = "Azure region for all resources."
  type        = string
  default     = "westeurope"
}

variable "prefix" {
  description = "Prefix used to name all resources (resource group, VM, identity, etc.)."
  type        = string
  default     = "teleport-azure"
}

variable "vm_size" {
  description = "Azure VM SKU for the Teleport Application Service host."
  type        = string
  default     = "Standard_B2s"
}

variable "admin_username" {
  description = "Admin user for the Linux VM."
  type        = string
  default     = "azureuser"
}

variable "admin_ssh_public_key_path" {
  description = "Path to the SSH public key (OpenSSH RSA format, ≥2048-bit — Azure rejects ed25519) authorized for the admin user on the Linux VM. Default points to the key generated by `make ssh-key`. Supports `~` expansion. Access the VM via `tsh ssh` once it joins the cluster; this key is a break-glass fallback."
  type        = string
  default     = "../id_rsa_azure.pub"
}

variable "teleport_proxy_address" {
  description = "Teleport proxy address, e.g. teleport.example.com:443. Used in the cloud-init bootstrap."
  type        = string
}

variable "teleport_app_name" {
  description = "Name of the Azure CLI application registered in Teleport."
  type        = string
  default     = "azure-cli"
}

variable "teleport_join_token_name" {
  description = "Name of the Teleport `kind: token` resource (type: azure) the VM uses to join."
  type        = string
  default     = "azure-token"
}
